-- ----------------------------
-- 1、部门表
-- ----------------------------
drop table if exists sys_dept;
create table sys_dept (
  dept_id           bigint        not null generated by default as identity,
  parent_id         bigint        default 0,
  ancestors         varchar(50)   default '',
  dept_name         varchar(30)   default '',
  order_num         integer       default 0,
  leader            varchar(20)   default null,
  phone             varchar(11)   default null,
  email             varchar(50)   default null,
  status            char(1)       default '0',
  del_flag          char(1)       default '0',
  create_by         varchar(64)   default '',
  create_time       timestamp,
  update_by         varchar(64)   default '',
  update_time       timestamp,
  primary key (dept_id)
);
comment on table sys_dept is '部门表';
comment on column sys_dept.dept_id is '部门id';
comment on column sys_dept.parent_id is '父部门id';
comment on column sys_dept.ancestors is '祖级列表';
comment on column sys_dept.dept_name is '部门名称';
comment on column sys_dept.order_num is '显示顺序';
comment on column sys_dept.leader is '负责人';
comment on column sys_dept.phone is '联系电话';
comment on column sys_dept.email is '邮箱';
comment on column sys_dept.status is '部门状态（0正常 1停用）';
comment on column sys_dept.del_flag is '删除标志（0代表存在 2代表删除）';
comment on column sys_dept.create_by is '创建者';
comment on column sys_dept.create_time is '创建时间';
comment on column sys_dept.update_by is '更新者';
comment on column sys_dept.update_time is '更新时间';

-- 部门：最小骨架 —— 富房 → 龙湖店 / 西派少城店 / 租赁部
insert into sys_dept values(100,   0, '0',             '富房',           1, '总部管理',   '', '', '0', '0', '0001', now(), '', null);
insert into sys_dept values(200, 100, '0,100',         '龙湖店',         1, '门店负责人', '', '', '0', '0', '0001', now(), '', null);
insert into sys_dept values(210, 100, '0,100',         '西派少城店',     1, '门店负责人', '', '', '0', '0', '0001', now(), '', null);
insert into sys_dept values(220, 100, '0,100',         '租赁部',         1, '部门负责人', '', '', '0', '0', '0001', now(), '', null);
select setval(pg_get_serial_sequence('sys_dept', 'dept_id'), (select max(dept_id) from sys_dept));


-- ----------------------------
-- 2、用户信息表
-- ----------------------------
drop table if exists sys_user;
create table sys_user (
  user_id           bigint        not null generated by default as identity,
  dept_id           bigint        default null,
  login_name        varchar(30)   not null,
  user_name         varchar(30)   default '',
  user_type         varchar(2)    default '00',
  email             varchar(50)   default '',
  phonenumber       varchar(11)   default '',
  sex               char(1)       default '0',
  avatar            varchar(100)  default '',
  password          varchar(50)   default '',
  salt              varchar(20)   default '',
  status            char(1)       default '0',
  del_flag          char(1)       default '0',
  login_ip          varchar(128)  default '',
  login_date        timestamp,
  pwd_update_date   timestamp,
  create_by         varchar(64)   default '',
  create_time       timestamp,
  update_by         varchar(64)   default '',
  update_time       timestamp,
  remark            varchar(500)  default null,
  primary key (user_id)
);
comment on table sys_user is '用户信息表';
comment on column sys_user.user_id is '用户ID';
comment on column sys_user.dept_id is '部门ID';
comment on column sys_user.login_name is '登录账号';
comment on column sys_user.user_name is '用户昵称';
comment on column sys_user.user_type is '用户类型（00系统用户 01注册用户）';
comment on column sys_user.email is '用户邮箱';
comment on column sys_user.phonenumber is '手机号码';
comment on column sys_user.sex is '用户性别（0男 1女 2未知）';
comment on column sys_user.avatar is '头像路径';
comment on column sys_user.password is '密码';
comment on column sys_user.salt is '盐加密';
comment on column sys_user.status is '账号状态（0正常 1停用）';
comment on column sys_user.del_flag is '删除标志（0代表存在 2代表删除）';
comment on column sys_user.login_ip is '最后登录IP';
comment on column sys_user.login_date is '最后登录时间';
comment on column sys_user.pwd_update_date is '密码最后更新时间';
comment on column sys_user.create_by is '创建者';
comment on column sys_user.create_time is '创建时间';
comment on column sys_user.update_by is '更新者';
comment on column sys_user.update_time is '更新时间';
comment on column sys_user.remark is '备注';

-- 用户：7 个（0001-0007 员工号登录），密码统一 admin123，salt=111111，hash = md5(login_name + 'admin123' + '111111')
-- 列顺序(user_id:1 dept_id:2 login_name:3 user_name:4 user_type:5 email:6 phonenumber:7 sex:8 avatar:9 password:10 salt:11 status:12 del_flag:13 login_ip:14 login_date:15 pwd_update_date:16 create_by:17 create_time:18 update_by:19 update_time:20 remark:21)
insert into sys_user values( 1, 100, '0001', '超级管理员','00','admin@panjia.com',  '13800000001','1','','80a5f5f7e719ab27e9126281646b35d3','111111','0','0','127.0.0.1',null,null,'0001',now(),'',null,'系统运维账户');
insert into sys_user values(10, 100, '0002', '王总',      '00','wang@panjia.com',   '13800000100','1','','b947283e3ae9e9e992af95b23cc5ae43','111111','0','0','',         null,null,'0001',now(),'',null,'公司股东 - 全公司');
insert into sys_user values(20, 200, '0003', '李老板',    '00','li@panjia.com',     '13800000200','1','','3ee401b82cdfd6204c67261f589b58de','111111','0','0','',         null,null,'0001',now(),'',null,'门店股东 - 龙湖店/参股');
insert into sys_user values(30, 200, '0004', '张秘书',    '00','zhang@panjia.com',  '13800000300','2','','4ba4301799c33081bf0e44fe6e5c6309','111111','0','0','',         null,null,'0001',now(),'',null,'店务秘书 - 龙湖店');
insert into sys_user values(40, 210, '0005', '赵组长',    '00','zhao@panjia.com',   '13800000400','1','','889c91265cd37c7e509938224fdd2429','111111','0','0','',         null,null,'0001',now(),'',null,'业务组长 - 西派少城店');
insert into sys_user values(50, 210, '0006', '钱经纪',    '00','qian@panjia.com',   '13800000500','1','','87e3d49a0b855c92a8b3a4fd16764f3e','111111','0','0','',         null,null,'0001',now(),'',null,'经纪人 - 西派少城店');
insert into sys_user values(60, 210, '0007', '孙见习',    '00','sun@panjia.com',    '13800000600','0','','cc87208f2287288642a53fb863ad9b48','111111','0','0','',         null,null,'0001',now(),'',null,'见习经纪人 - 西派少城店');
select setval(pg_get_serial_sequence('sys_user', 'user_id'), (select max(user_id) from sys_user));


-- ----------------------------
-- 3、岗位信息表
-- ----------------------------
drop table if exists sys_post;
create table sys_post
(
  post_id       bigint        not null generated by default as identity,
  post_code     varchar(64)   not null,
  post_name     varchar(50)   not null,
  post_sort     integer       not null,
  status        char(1)       not null,
  create_by     varchar(64)   default '',
  create_time   timestamp,
  update_by     varchar(64)   default '',
  update_time   timestamp,
  remark        varchar(500)  default null,
  primary key (post_id)
);
comment on table sys_post is '岗位信息表';
comment on column sys_post.post_id is '岗位ID';
comment on column sys_post.post_code is '岗位编码';
comment on column sys_post.post_name is '岗位名称';
comment on column sys_post.post_sort is '显示顺序';
comment on column sys_post.status is '状态（0正常 1停用）';
comment on column sys_post.create_by is '创建者';
comment on column sys_post.create_time is '创建时间';
comment on column sys_post.update_by is '更新者';
comment on column sys_post.update_time is '更新时间';
comment on column sys_post.remark is '备注';

-- 岗位（1:1 对应业务角色 6 类）
insert into sys_post values(1, 'shareholder', '公司股东',   1, '0', '0001', now(), '', null, '');
insert into sys_post values(2, 'shopowner',   '门店股东',   2, '0', '0001', now(), '', null, '');
insert into sys_post values(3, 'secretary',   '店务秘书',   3, '0', '0001', now(), '', null, '');
insert into sys_post values(4, 'teamleader',  '业务组长',   4, '0', '0001', now(), '', null, '');
insert into sys_post values(5, 'agent',       '经纪人',     5, '0', '0001', now(), '', null, '');
insert into sys_post values(6, 'trainee',     '见习经纪人', 6, '0', '0001', now(), '', null, '');
select setval(pg_get_serial_sequence('sys_post', 'post_id'), (select max(post_id) from sys_post));


-- ----------------------------
-- 4、角色信息表
-- ----------------------------
drop table if exists sys_role;
create table sys_role (
  role_id           bigint        not null generated by default as identity,
  role_name         varchar(30)   not null,
  role_key          varchar(100)  not null,
  role_sort         integer       not null,
  data_scope        char(1)       default '1',
  status            char(1)       not null,
  del_flag          char(1)       default '0',
  create_by         varchar(64)   default '',
  create_time       timestamp,
  update_by         varchar(64)   default '',
  update_time       timestamp,
  remark            varchar(500)  default null,
  primary key (role_id)
);
comment on table sys_role is '角色信息表';
comment on column sys_role.role_id is '角色ID';
comment on column sys_role.role_name is '角色名称';
comment on column sys_role.role_key is '角色权限字符串';
comment on column sys_role.role_sort is '显示顺序';
comment on column sys_role.data_scope is '数据范围（1：全部数据权限 2：自定数据权限 3：本部门数据权限 4：本部门及以下数据权限）';
comment on column sys_role.status is '角色状态（0正常 1停用）';
comment on column sys_role.del_flag is '删除标志（0代表存在 2代表删除）';
comment on column sys_role.create_by is '创建者';
comment on column sys_role.create_time is '创建时间';
comment on column sys_role.update_by is '更新者';
comment on column sys_role.update_time is '更新时间';
comment on column sys_role.remark is '备注';

-- 角色：7 类（数据范围 1=全公司 2=自定义 3=本部门 4=本部门及以下 5=仅本人）
insert into sys_role values(1, '超级管理员', 'admin',        1, '1', '0', '0', '0001', now(), '', null, '系统最高权限，运维专用');
insert into sys_role values(2, '公司股东',   'shareholder',  2, '1', '0', '0', '0001', now(), '', null, '全公司数据范围，跨店运营');
insert into sys_role values(3, '门店股东',   'shopowner',    3, '2', '0', '0', '0001', now(), '', null, '自定义范围：本店+参股门店（sys_role_dept 勾选）');
insert into sys_role values(4, '店务秘书',   'secretary',    4, '4', '0', '0', '0001', now(), '', null, '本部门及以下=本店及所有业务组');
insert into sys_role values(5, '业务组长',   'teamleader',   5, '3', '0', '0', '0001', now(), '', null, '本部门=本组');
insert into sys_role values(6, '经纪人',     'agent',        6, '5', '0', '0', '0001', now(), '', null, '仅本人');
insert into sys_role values(7, '见习经纪人', 'trainee',      7, '5', '0', '0', '0001', now(), '', null, '仅本人，操作受限');
select setval(pg_get_serial_sequence('sys_role', 'role_id'), (select max(role_id) from sys_role));


-- ----------------------------
-- 5、菜单权限表
-- ----------------------------
drop table if exists sys_menu;
create table sys_menu (
  menu_id           bigint        not null generated by default as identity,
  menu_name         varchar(50)   not null,
  parent_id         bigint        default 0,
  order_num         integer       default 0,
  url               varchar(200)  default '#',
  target            varchar(20)   default '',
  menu_type         char(1)       default '',
  visible           char(1)       default '0',
  is_refresh        char(1)       default '1',
  perms             varchar(100)  default null,
  icon              varchar(100)  default '#',
  create_by         varchar(64)   default '',
  create_time       timestamp,
  update_by         varchar(64)   default '',
  update_time       timestamp,
  remark            varchar(500)  default '',
  primary key (menu_id)
);
comment on table sys_menu is '菜单权限表';
comment on column sys_menu.menu_id is '菜单ID';
comment on column sys_menu.menu_name is '菜单名称';
comment on column sys_menu.parent_id is '父菜单ID';
comment on column sys_menu.order_num is '显示顺序';
comment on column sys_menu.url is '请求地址';
comment on column sys_menu.target is '打开方式（menuItem页签 menuBlank新窗口）';
comment on column sys_menu.menu_type is '菜单类型（M目录 C菜单 F按钮）';
comment on column sys_menu.visible is '菜单状态（0显示 1隐藏）';
comment on column sys_menu.is_refresh is '是否刷新（0刷新 1不刷新）';
comment on column sys_menu.perms is '权限标识';
comment on column sys_menu.icon is '菜单图标';
comment on column sys_menu.create_by is '创建者';
comment on column sys_menu.create_time is '创建时间';
comment on column sys_menu.update_by is '更新者';
comment on column sys_menu.update_time is '更新时间';
comment on column sys_menu.remark is '备注';

-- 菜单裁剪：去掉 系统工具(3)/若依官网(4)/表单构建(114)/代码生成(115)/系统接口(116)/生成权限按钮(1057-1061)/通知公告(107)+按钮(1035-1038)/数据监控(111)/服务监控(112)/缓存监控(113)
-- 仅保留：系统管理 + 系统监控（在线用户/定时任务 + 日志）
insert into sys_menu values('1', '系统管理', '0', '1', '#', '', 'M', '0', '1', '', 'fa fa-gear', '0001', now(), '', null, '系统管理目录');
insert into sys_menu values('2', '系统监控', '0', '2', '#', '', 'M', '0', '1', '', 'fa fa-video-camera', '0001', now(), '', null, '系统监控目录');
insert into sys_menu values('100', '用户管理', '1', '1', '/system/user', '', 'C', '0', '1', 'system:user:view', 'fa fa-user-o', '0001', now(), '', null, '用户管理菜单');
insert into sys_menu values('101', '角色管理', '1', '2', '/system/role', '', 'C', '0', '1', 'system:role:view', 'fa fa-user-secret', '0001', now(), '', null, '角色管理菜单');
insert into sys_menu values('102', '菜单管理', '1', '3', '/system/menu', '', 'C', '0', '1', 'system:menu:view', 'fa fa-th-list', '0001', now(), '', null, '菜单管理菜单');
insert into sys_menu values('103', '部门管理', '1', '4', '/system/dept', '', 'C', '0', '1', 'system:dept:view', 'fa fa-outdent', '0001', now(), '', null, '部门管理菜单');
insert into sys_menu values('104', '岗位管理', '1', '5', '/system/post', '', 'C', '0', '1', 'system:post:view', 'fa fa-address-card-o', '0001', now(), '', null, '岗位管理菜单');
insert into sys_menu values('105', '字典管理', '1', '6', '/system/dict', '', 'C', '0', '1', 'system:dict:view', 'fa fa-bookmark-o', '0001', now(), '', null, '字典管理菜单');
insert into sys_menu values('106', '参数设置', '1', '7', '/system/config', '', 'C', '0', '1', 'system:config:view', 'fa fa-sun-o', '0001', now(), '', null, '参数设置菜单');
insert into sys_menu values('108', '日志管理', '1', '9', '#', '', 'M', '0', '1', '', 'fa fa-pencil-square-o', '0001', now(), '', null, '日志管理菜单');
insert into sys_menu values('109', '在线用户', '2', '1', '/monitor/online', '', 'C', '0', '1', 'monitor:online:view', 'fa fa-user-circle', '0001', now(), '', null, '在线用户菜单');
insert into sys_menu values('110', '定时任务', '2', '2', '/monitor/job', '', 'C', '0', '1', 'monitor:job:view', 'fa fa-tasks', '0001', now(), '', null, '定时任务菜单');
insert into sys_menu values('500', '操作日志', '108', '1', '/monitor/operlog', '', 'C', '0', '1', 'monitor:operlog:view', 'fa fa-address-book', '0001', now(), '', null, '操作日志菜单');
insert into sys_menu values('501', '登录日志', '108', '2', '/monitor/logininfor', '', 'C', '0', '1', 'monitor:logininfor:view', 'fa fa-file-image-o', '0001', now(), '', null, '登录日志菜单');
insert into sys_menu values('1000', '用户查询', '100', '1', '#', '', 'F', '0', '1', 'system:user:list', '#', '0001', now(), '', null, '');
insert into sys_menu values('1001', '用户新增', '100', '2', '#', '', 'F', '0', '1', 'system:user:add', '#', '0001', now(), '', null, '');
insert into sys_menu values('1002', '用户修改', '100', '3', '#', '', 'F', '0', '1', 'system:user:edit', '#', '0001', now(), '', null, '');
insert into sys_menu values('1003', '用户删除', '100', '4', '#', '', 'F', '0', '1', 'system:user:remove', '#', '0001', now(), '', null, '');
insert into sys_menu values('1004', '用户导出', '100', '5', '#', '', 'F', '0', '1', 'system:user:export', '#', '0001', now(), '', null, '');
insert into sys_menu values('1005', '用户导入', '100', '6', '#', '', 'F', '0', '1', 'system:user:import', '#', '0001', now(), '', null, '');
insert into sys_menu values('1006', '重置密码', '100', '7', '#', '', 'F', '0', '1', 'system:user:resetPwd', '#', '0001', now(), '', null, '');
insert into sys_menu values('1007', '角色查询', '101', '1', '#', '', 'F', '0', '1', 'system:role:list', '#', '0001', now(), '', null, '');
insert into sys_menu values('1008', '角色新增', '101', '2', '#', '', 'F', '0', '1', 'system:role:add', '#', '0001', now(), '', null, '');
insert into sys_menu values('1009', '角色修改', '101', '3', '#', '', 'F', '0', '1', 'system:role:edit', '#', '0001', now(), '', null, '');
insert into sys_menu values('1010', '角色删除', '101', '4', '#', '', 'F', '0', '1', 'system:role:remove', '#', '0001', now(), '', null, '');
insert into sys_menu values('1011', '角色导出', '101', '5', '#', '', 'F', '0', '1', 'system:role:export', '#', '0001', now(), '', null, '');
insert into sys_menu values('1012', '菜单查询', '102', '1', '#', '', 'F', '0', '1', 'system:menu:list', '#', '0001', now(), '', null, '');
insert into sys_menu values('1013', '菜单新增', '102', '2', '#', '', 'F', '0', '1', 'system:menu:add', '#', '0001', now(), '', null, '');
insert into sys_menu values('1014', '菜单修改', '102', '3', '#', '', 'F', '0', '1', 'system:menu:edit', '#', '0001', now(), '', null, '');
insert into sys_menu values('1015', '菜单删除', '102', '4', '#', '', 'F', '0', '1', 'system:menu:remove', '#', '0001', now(), '', null, '');
insert into sys_menu values('1016', '部门查询', '103', '1', '#', '', 'F', '0', '1', 'system:dept:list', '#', '0001', now(), '', null, '');
insert into sys_menu values('1017', '部门新增', '103', '2', '#', '', 'F', '0', '1', 'system:dept:add', '#', '0001', now(), '', null, '');
insert into sys_menu values('1018', '部门修改', '103', '3', '#', '', 'F', '0', '1', 'system:dept:edit', '#', '0001', now(), '', null, '');
insert into sys_menu values('1019', '部门删除', '103', '4', '#', '', 'F', '0', '1', 'system:dept:remove', '#', '0001', now(), '', null, '');
insert into sys_menu values('1020', '岗位查询', '104', '1', '#', '', 'F', '0', '1', 'system:post:list', '#', '0001', now(), '', null, '');
insert into sys_menu values('1021', '岗位新增', '104', '2', '#', '', 'F', '0', '1', 'system:post:add', '#', '0001', now(), '', null, '');
insert into sys_menu values('1022', '岗位修改', '104', '3', '#', '', 'F', '0', '1', 'system:post:edit', '#', '0001', now(), '', null, '');
insert into sys_menu values('1023', '岗位删除', '104', '4', '#', '', 'F', '0', '1', 'system:post:remove', '#', '0001', now(), '', null, '');
insert into sys_menu values('1024', '岗位导出', '104', '5', '#', '', 'F', '0', '1', 'system:post:export', '#', '0001', now(), '', null, '');
insert into sys_menu values('1025', '字典查询', '105', '1', '#', '', 'F', '0', '1', 'system:dict:list', '#', '0001', now(), '', null, '');
insert into sys_menu values('1026', '字典新增', '105', '2', '#', '', 'F', '0', '1', 'system:dict:add', '#', '0001', now(), '', null, '');
insert into sys_menu values('1027', '字典修改', '105', '3', '#', '', 'F', '0', '1', 'system:dict:edit', '#', '0001', now(), '', null, '');
insert into sys_menu values('1028', '字典删除', '105', '4', '#', '', 'F', '0', '1', 'system:dict:remove', '#', '0001', now(), '', null, '');
insert into sys_menu values('1029', '字典导出', '105', '5', '#', '', 'F', '0', '1', 'system:dict:export', '#', '0001', now(), '', null, '');
insert into sys_menu values('1030', '参数查询', '106', '1', '#', '', 'F', '0', '1', 'system:config:list', '#', '0001', now(), '', null, '');
insert into sys_menu values('1031', '参数新增', '106', '2', '#', '', 'F', '0', '1', 'system:config:add', '#', '0001', now(), '', null, '');
insert into sys_menu values('1032', '参数修改', '106', '3', '#', '', 'F', '0', '1', 'system:config:edit', '#', '0001', now(), '', null, '');
insert into sys_menu values('1033', '参数删除', '106', '4', '#', '', 'F', '0', '1', 'system:config:remove', '#', '0001', now(), '', null, '');
insert into sys_menu values('1034', '参数导出', '106', '5', '#', '', 'F', '0', '1', 'system:config:export', '#', '0001', now(), '', null, '');
insert into sys_menu values('1039', '操作查询', '500', '1', '#', '', 'F', '0', '1', 'monitor:operlog:list', '#', '0001', now(), '', null, '');
insert into sys_menu values('1040', '操作删除', '500', '2', '#', '', 'F', '0', '1', 'monitor:operlog:remove', '#', '0001', now(), '', null, '');
insert into sys_menu values('1041', '详细信息', '500', '3', '#', '', 'F', '0', '1', 'monitor:operlog:detail', '#', '0001', now(), '', null, '');
insert into sys_menu values('1042', '日志导出', '500', '4', '#', '', 'F', '0', '1', 'monitor:operlog:export', '#', '0001', now(), '', null, '');
insert into sys_menu values('1043', '登录查询', '501', '1', '#', '', 'F', '0', '1', 'monitor:logininfor:list', '#', '0001', now(), '', null, '');
insert into sys_menu values('1044', '登录删除', '501', '2', '#', '', 'F', '0', '1', 'monitor:logininfor:remove', '#', '0001', now(), '', null, '');
insert into sys_menu values('1045', '日志导出', '501', '3', '#', '', 'F', '0', '1', 'monitor:logininfor:export', '#', '0001', now(), '', null, '');
insert into sys_menu values('1046', '账户解锁', '501', '4', '#', '', 'F', '0', '1', 'monitor:logininfor:unlock', '#', '0001', now(), '', null, '');
insert into sys_menu values('1047', '在线查询', '109', '1', '#', '', 'F', '0', '1', 'monitor:online:list', '#', '0001', now(), '', null, '');
insert into sys_menu values('1048', '批量强退', '109', '2', '#', '', 'F', '0', '1', 'monitor:online:batchForceLogout', '#', '0001', now(), '', null, '');
insert into sys_menu values('1049', '单条强退', '109', '3', '#', '', 'F', '0', '1', 'monitor:online:forceLogout', '#', '0001', now(), '', null, '');
insert into sys_menu values('1050', '任务查询', '110', '1', '#', '', 'F', '0', '1', 'monitor:job:list', '#', '0001', now(), '', null, '');
insert into sys_menu values('1051', '任务新增', '110', '2', '#', '', 'F', '0', '1', 'monitor:job:add', '#', '0001', now(), '', null, '');
insert into sys_menu values('1052', '任务修改', '110', '3', '#', '', 'F', '0', '1', 'monitor:job:edit', '#', '0001', now(), '', null, '');
insert into sys_menu values('1053', '任务删除', '110', '4', '#', '', 'F', '0', '1', 'monitor:job:remove', '#', '0001', now(), '', null, '');
insert into sys_menu values('1054', '状态修改', '110', '5', '#', '', 'F', '0', '1', 'monitor:job:changeStatus', '#', '0001', now(), '', null, '');
insert into sys_menu values('1055', '任务详细', '110', '6', '#', '', 'F', '0', '1', 'monitor:job:detail', '#', '0001', now(), '', null, '');
insert into sys_menu values('1056', '任务导出', '110', '7', '#', '', 'F', '0', '1', 'monitor:job:export', '#', '0001', now(), '', null, '');
select setval(pg_get_serial_sequence('sys_menu', 'menu_id'), (select max(menu_id) from sys_menu));


-- ----------------------------
-- 6、用户和角色关联表  用户N-1角色
-- ----------------------------
drop table if exists sys_user_role;
create table sys_user_role (
  user_id   bigint not null,
  role_id   bigint not null,
  primary key(user_id, role_id)
);
comment on table sys_user_role is '用户和角色关联表';
comment on column sys_user_role.user_id is '用户ID';
comment on column sys_user_role.role_id is '角色ID';

-- 用户-角色：7 条 1:1
insert into sys_user_role values ( 1, 1);
insert into sys_user_role values (10, 2);
insert into sys_user_role values (20, 3);
insert into sys_user_role values (30, 4);
insert into sys_user_role values (40, 5);
insert into sys_user_role values (50, 6);
insert into sys_user_role values (60, 7);


-- ----------------------------
-- 7、角色和菜单关联表  角色1-N菜单
-- ----------------------------
drop table if exists sys_role_menu;
create table sys_role_menu (
  role_id   bigint not null,
  menu_id   bigint not null,
  primary key(role_id, menu_id)
);
comment on table sys_role_menu is '角色和菜单关联表';
comment on column sys_role_menu.role_id is '角色ID';
comment on column sys_role_menu.menu_id is '菜单ID';

-- 角色-菜单：角色 1/2/3/4（超级/公司/门店/秘书）= 后台全量菜单；5/6/7（组长/经纪/见习）= 不进后台，空
INSERT INTO sys_role_menu (role_id, menu_id)
SELECT r, m FROM (VALUES (1),(2),(3),(4)) roles(r), sys_menu menus(m);


-- ----------------------------
-- 8、角色和部门关联表  角色1-N部门
-- ----------------------------
drop table if exists sys_role_dept;
create table sys_role_dept (
  role_id   bigint not null,
  dept_id   bigint not null,
  primary key(role_id, dept_id)
);
comment on table sys_role_dept is '角色和部门关联表';
comment on column sys_role_dept.role_id is '角色ID';
comment on column sys_role_dept.dept_id is '部门ID';

-- 角色-部门：仅 role_id=3（门店股东，自定义数据范围）勾选参股门店 = 龙湖店 + 西派少城店 + 租赁部
insert into sys_role_dept values (3, 200);
insert into sys_role_dept values (3, 210);
insert into sys_role_dept values (3, 220);


-- ----------------------------
-- 9、用户与岗位关联表  用户1-N岗位
-- ----------------------------
drop table if exists sys_user_post;
create table sys_user_post
(
  user_id   bigint not null,
  post_id   bigint not null,
  primary key (user_id, post_id)
);
comment on table sys_user_post is '用户与岗位关联表';
comment on column sys_user_post.user_id is '用户ID';
comment on column sys_user_post.post_id is '岗位ID';

-- 用户-岗位：6 个业务用户各挂 1 个岗位（admin 运维账号不挂岗位）
insert into sys_user_post values (10, 1);
insert into sys_user_post values (20, 2);
insert into sys_user_post values (30, 3);
insert into sys_user_post values (40, 4);
insert into sys_user_post values (50, 5);
insert into sys_user_post values (60, 6);


-- ----------------------------
-- 10、操作日志记录
-- ----------------------------
drop table if exists sys_oper_log;
create table sys_oper_log (
  oper_id           bigint        not null generated by default as identity,
  title             varchar(50)   default '',
  business_type     integer       default 0,
  method            varchar(200)  default '',
  request_method    varchar(10)   default '',
  operator_type     integer       default 0,
  oper_name         varchar(50)   default '',
  dept_name         varchar(50)   default '',
  oper_url          varchar(255)  default '',
  oper_ip           varchar(128)  default '',
  oper_location     varchar(255)  default '',
  oper_param        varchar(2000) default '',
  json_result       varchar(2000) default '',
  status            integer       default 0,
  error_msg         varchar(2000) default '',
  oper_time         timestamp,
  cost_time         bigint        default 0,
  primary key (oper_id)
);
comment on table sys_oper_log is '操作日志记录';
comment on column sys_oper_log.oper_id is '日志主键';
comment on column sys_oper_log.title is '模块标题';
comment on column sys_oper_log.business_type is '业务类型（0其它 1新增 2修改 3删除）';
comment on column sys_oper_log.method is '方法名称';
comment on column sys_oper_log.request_method is '请求方式';
comment on column sys_oper_log.operator_type is '操作类别（0其它 1后台用户 2手机端用户）';
comment on column sys_oper_log.oper_name is '操作人员';
comment on column sys_oper_log.dept_name is '部门名称';
comment on column sys_oper_log.oper_url is '请求URL';
comment on column sys_oper_log.oper_ip is '主机地址';
comment on column sys_oper_log.oper_location is '操作地点';
comment on column sys_oper_log.oper_param is '请求参数';
comment on column sys_oper_log.json_result is '返回参数';
comment on column sys_oper_log.status is '操作状态（0正常 1异常）';
comment on column sys_oper_log.error_msg is '错误消息';
comment on column sys_oper_log.oper_time is '操作时间';
comment on column sys_oper_log.cost_time is '消耗时间';

create index idx_sys_oper_log_bt on sys_oper_log(business_type);
create index idx_sys_oper_log_s on sys_oper_log(status);
create index idx_sys_oper_log_ot on sys_oper_log(oper_time);
select setval(pg_get_serial_sequence('sys_oper_log', 'oper_id'), (select max(oper_id) from sys_oper_log));


-- ----------------------------
-- 11、字典类型表
-- ----------------------------
drop table if exists sys_dict_type;
create table sys_dict_type
(
  dict_id          bigint        not null generated by default as identity,
  dict_name        varchar(100)  default '',
  dict_type        varchar(100)  default '',
  status           char(1)       default '0',
  create_by        varchar(64)   default '',
  create_time      timestamp,
  update_by        varchar(64)   default '',
  update_time      timestamp,
  remark           varchar(500)  default null,
  primary key (dict_id),
  unique (dict_type)
);
comment on table sys_dict_type is '字典类型表';
comment on column sys_dict_type.dict_id is '字典主键';
comment on column sys_dict_type.dict_name is '字典名称';
comment on column sys_dict_type.dict_type is '字典类型';
comment on column sys_dict_type.status is '状态（0正常 1停用）';
comment on column sys_dict_type.create_by is '创建者';
comment on column sys_dict_type.create_time is '创建时间';
comment on column sys_dict_type.update_by is '更新者';
comment on column sys_dict_type.update_time is '更新时间';
comment on column sys_dict_type.remark is '备注';

insert into sys_dict_type values(1,  '用户性别', 'sys_user_sex',        '0', '0001', now(), '', null, '用户性别列表');
insert into sys_dict_type values(2,  '菜单状态', 'sys_show_hide',       '0', '0001', now(), '', null, '菜单状态列表');
insert into sys_dict_type values(3,  '系统开关', 'sys_normal_disable',  '0', '0001', now(), '', null, '系统开关列表');
insert into sys_dict_type values(4,  '任务状态', 'sys_job_status',      '0', '0001', now(), '', null, '任务状态列表');
insert into sys_dict_type values(5,  '任务分组', 'sys_job_group',       '0', '0001', now(), '', null, '任务分组列表');
insert into sys_dict_type values(6,  '系统是否', 'sys_yes_no',          '0', '0001', now(), '', null, '系统是否列表');
insert into sys_dict_type values(9,  '操作类型', 'sys_oper_type',       '0', '0001', now(), '', null, '操作类型列表');
insert into sys_dict_type values(10, '系统状态', 'sys_common_status',   '0', '0001', now(), '', null, '登录状态列表');
select setval(pg_get_serial_sequence('sys_dict_type', 'dict_id'), (select max(dict_id) from sys_dict_type));


-- ----------------------------
-- 12、字典数据表
-- ----------------------------
drop table if exists sys_dict_data;
create table sys_dict_data
(
  dict_code        bigint        not null generated by default as identity,
  dict_sort        integer       default 0,
  dict_label       varchar(100)  default '',
  dict_value       varchar(100)  default '',
  dict_type        varchar(100)  default '',
  css_class        varchar(100)  default null,
  list_class       varchar(100)  default null,
  is_default       char(1)       default 'N',
  status           char(1)       default '0',
  create_by        varchar(64)   default '',
  create_time      timestamp,
  update_by        varchar(64)   default '',
  update_time      timestamp,
  remark           varchar(500)  default null,
  primary key (dict_code)
);
comment on table sys_dict_data is '字典数据表';
comment on column sys_dict_data.dict_code is '字典编码';
comment on column sys_dict_data.dict_sort is '字典排序';
comment on column sys_dict_data.dict_label is '字典标签';
comment on column sys_dict_data.dict_value is '字典键值';
comment on column sys_dict_data.dict_type is '字典类型';
comment on column sys_dict_data.css_class is '样式属性（其他样式扩展）';
comment on column sys_dict_data.list_class is '表格回显样式';
comment on column sys_dict_data.is_default is '是否默认（Y是 N否）';
comment on column sys_dict_data.status is '状态（0正常 1停用）';
comment on column sys_dict_data.create_by is '创建者';
comment on column sys_dict_data.create_time is '创建时间';
comment on column sys_dict_data.update_by is '更新者';
comment on column sys_dict_data.update_time is '更新时间';
comment on column sys_dict_data.remark is '备注';

insert into sys_dict_data values(1,  1,  '男',       '0',       'sys_user_sex',        '',   '',        'Y', '0', '0001', now(), '', null, '性别男');
insert into sys_dict_data values(2,  2,  '女',       '1',       'sys_user_sex',        '',   '',        'N', '0', '0001', now(), '', null, '性别女');
insert into sys_dict_data values(3,  3,  '未知',     '2',       'sys_user_sex',        '',   '',        'N', '0', '0001', now(), '', null, '性别未知');
insert into sys_dict_data values(4,  1,  '显示',     '0',       'sys_show_hide',       '',   'primary', 'Y', '0', '0001', now(), '', null, '显示菜单');
insert into sys_dict_data values(5,  2,  '隐藏',     '1',       'sys_show_hide',       '',   'danger',  'N', '0', '0001', now(), '', null, '隐藏菜单');
insert into sys_dict_data values(6,  1,  '正常',     '0',       'sys_normal_disable',  '',   'primary', 'Y', '0', '0001', now(), '', null, '正常状态');
insert into sys_dict_data values(7,  2,  '停用',     '1',       'sys_normal_disable',  '',   'danger',  'N', '0', '0001', now(), '', null, '停用状态');
insert into sys_dict_data values(8,  1,  '正常',     '0',       'sys_job_status',      '',   'primary', 'Y', '0', '0001', now(), '', null, '正常状态');
insert into sys_dict_data values(9,  2,  '暂停',     '1',       'sys_job_status',      '',   'danger',  'N', '0', '0001', now(), '', null, '停用状态');
insert into sys_dict_data values(10, 1,  '默认',     'DEFAULT', 'sys_job_group',       '',   '',        'Y', '0', '0001', now(), '', null, '默认分组');
insert into sys_dict_data values(11, 2,  '系统',     'SYSTEM',  'sys_job_group',       '',   '',        'N', '0', '0001', now(), '', null, '系统分组');
insert into sys_dict_data values(12, 1,  '是',       'Y',       'sys_yes_no',          '',   'primary', 'Y', '0', '0001', now(), '', null, '系统默认是');
insert into sys_dict_data values(13, 2,  '否',       'N',       'sys_yes_no',          '',   'danger',  'N', '0', '0001', now(), '', null, '系统默认否');
insert into sys_dict_data values(18, 99, '其他',     '0',       'sys_oper_type',       '',   'info',    'N', '0', '0001', now(), '', null, '其他操作');
insert into sys_dict_data values(19, 1,  '新增',     '1',       'sys_oper_type',       '',   'info',    'N', '0', '0001', now(), '', null, '新增操作');
insert into sys_dict_data values(20, 2,  '修改',     '2',       'sys_oper_type',       '',   'info',    'N', '0', '0001', now(), '', null, '修改操作');
insert into sys_dict_data values(21, 3,  '删除',     '3',       'sys_oper_type',       '',   'danger',  'N', '0', '0001', now(), '', null, '删除操作');
insert into sys_dict_data values(22, 4,  '授权',     '4',       'sys_oper_type',       '',   'primary', 'N', '0', '0001', now(), '', null, '授权操作');
insert into sys_dict_data values(23, 5,  '导出',     '5',       'sys_oper_type',       '',   'warning', 'N', '0', '0001', now(), '', null, '导出操作');
insert into sys_dict_data values(24, 6,  '导入',     '6',       'sys_oper_type',       '',   'warning', 'N', '0', '0001', now(), '', null, '导入操作');
insert into sys_dict_data values(25, 7,  '强退',     '7',       'sys_oper_type',       '',   'danger',  'N', '0', '0001', now(), '', null, '强退操作');
insert into sys_dict_data values(27, 9,  '清空数据', '9',       'sys_oper_type',       '',   'danger',  'N', '0', '0001', now(), '', null, '清空操作');
insert into sys_dict_data values(28, 1,  '成功',     '0',       'sys_common_status',   '',   'primary', 'N', '0', '0001', now(), '', null, '正常状态');
insert into sys_dict_data values(29, 2,  '失败',     '1',       'sys_common_status',   '',   'danger',  'N', '0', '0001', now(), '', null, '停用状态');
select setval(pg_get_serial_sequence('sys_dict_data', 'dict_code'), (select max(dict_code) from sys_dict_data));


-- ----------------------------
-- 13、参数配置表
-- ----------------------------
drop table if exists sys_config;
create table sys_config (
  config_id         bigint        not null generated by default as identity,
  config_name       varchar(100)  default '',
  config_key        varchar(100)  default '',
  config_value      varchar(500)  default '',
  config_type       char(1)       default 'N',
  create_by         varchar(64)   default '',
  create_time       timestamp,
  update_by         varchar(64)   default '',
  update_time       timestamp,
  remark            varchar(500)  default null,
  primary key (config_id)
);
comment on table sys_config is '参数配置表';
comment on column sys_config.config_id is '参数主键';
comment on column sys_config.config_name is '参数名称';
comment on column sys_config.config_key is '参数键名';
comment on column sys_config.config_value is '参数键值';
comment on column sys_config.config_type is '系统内置（Y是 N否）';
comment on column sys_config.create_by is '创建者';
comment on column sys_config.create_time is '创建时间';
comment on column sys_config.update_by is '更新者';
comment on column sys_config.update_time is '更新时间';
comment on column sys_config.remark is '备注';

insert into sys_config values(1, '主框架页-默认皮肤', 'sys.index.skinName',                 'skin-blue',      'Y', '0001', now(), '', null, '主框架页-默认皮肤');
insert into sys_config values(2, '主框架页-侧边栏主题', 'sys.side.theme',                    'theme-dark',     'Y', '0001', now(), '', null, '主框架页-侧边栏主题');
insert into sys_config values(3, '主框架页-侧边栏模式', 'sys.side.menuMode',                 'side-vertical',  'Y', '0001', now(), '', null, '主框架页-侧边栏模式');
insert into sys_config values(4, '用户账号密码最小长度', 'sys.user.initPassword.minLength',   '6',              'Y', '0001', now(), '', null, '用户账号密码最小长度');
insert into sys_config values(5, '用户账号密码最大长度', 'sys.user.initPassword.maxLength',   '20',             'Y', '0001', now(), '', null, '用户账号密码最大长度');
insert into sys_config values(6, '账号初始密码',         'sys.user.initPassword',             '123456',         'Y', '0001', now(), '', null, '账号初始密码');
insert into sys_config values(7, '主框架页-系统Logo',    'sys.index.logo',                    '/logo.png',      'Y', '0001', now(), '', null, '主框架页-系统Logo');
insert into sys_config values(8, '主框架页-主标题',      'sys.index.title',                   '盘家管理系统',    'Y', '0001', now(), '', null, '主框架页-主标题');
insert into sys_config values(9, '主框架页-副标题',      'sys.index.subTitle',                '房地产中介管理系统',    'Y', '0001', now(), '', null, '主框架页-副标题');
select setval(pg_get_serial_sequence('sys_config', 'config_id'), (select max(config_id) from sys_config));


-- ----------------------------
-- 14、系统访问记录
-- ----------------------------
drop table if exists sys_logininfor;
create table sys_logininfor (
  info_id           bigint        not null generated by default as identity,
  login_name        varchar(50)   default '',
  ipaddr            varchar(128)  default '',
  login_location    varchar(255)  default '',
  browser           varchar(50)   default '',
  os                varchar(50)   default '',
  status            char(1)       default '0',
  msg               varchar(255)  default '',
  login_time        timestamp,
  primary key (info_id)
);
comment on table sys_logininfor is '系统访问记录';
comment on column sys_logininfor.info_id is '访问记录主键';
comment on column sys_logininfor.login_name is '用户账号';
comment on column sys_logininfor.ipaddr is '登录IP地址';
comment on column sys_logininfor.login_location is '登录地点';
comment on column sys_logininfor.browser is '浏览器类型';
comment on column sys_logininfor.os is '操作系统';
comment on column sys_logininfor.status is '登录状态（0成功 1失败）';
comment on column sys_logininfor.msg is '提示消息';
comment on column sys_logininfor.login_time is '访问时间';

create index idx_sys_logininfor_lt on sys_logininfor(login_time);
create index idx_sys_logininfor_s on sys_logininfor(status);
select setval(pg_get_serial_sequence('sys_logininfor', 'info_id'), (select max(info_id) from sys_logininfor));


-- ----------------------------
-- 16、定时任务调度表
-- ----------------------------
drop table if exists sys_job;
create table sys_job (
  job_id              bigint        not null generated by default as identity,
  job_name            varchar(64)   default '',
  job_group           varchar(64)   default '',
  invoke_target       varchar(500)  default '',
  cron_expression     varchar(255)  default '',
  misfire_policy      varchar(20)   default '',
  concurrent          char(1)       default '',
  status              char(1)       default '0',
  create_by           varchar(64)   default '',
  create_time         timestamp,
  update_by           varchar(64)   default '',
  update_time         timestamp,
  remark              varchar(500)  default null,
  primary key (job_id)
);
comment on table sys_job is '定时任务调度表';
comment on column sys_job.job_id is '任务主键';
comment on column sys_job.job_name is '任务名称';
comment on column sys_job.job_group is '任务组名';
comment on column sys_job.invoke_target is '调用目标字符串';
comment on column sys_job.cron_expression is 'cron执行表达式';
comment on column sys_job.misfire_policy is '计划执行错误策略（1立即执行 2执行一次 3放弃执行）';
comment on column sys_job.concurrent is '是否并发执行（0允许 1禁止）';
comment on column sys_job.status is '状态（0正常 1暂停）';
comment on column sys_job.create_by is '创建者';
comment on column sys_job.create_time is '创建时间';
comment on column sys_job.update_by is '更新者';
comment on column sys_job.update_time is '更新时间';
comment on column sys_job.remark is '备注信息';

select setval(pg_get_serial_sequence('sys_job', 'job_id'), (select max(job_id) from sys_job));


-- ----------------------------
-- 17、定时任务调度日志表
-- ----------------------------
drop table if exists sys_job_log;
create table sys_job_log (
  job_log_id         bigint        not null generated by default as identity,
  job_name           varchar(64)   default '',
  job_group          varchar(64)   default '',
  invoke_target      varchar(500)  default '',
  status             char(1)       default '0',
  msg                varchar(255)  default '',
  create_time        timestamp,
  primary key (job_log_id)
);
comment on table sys_job_log is '定时任务调度日志表';
comment on column sys_job_log.job_log_id is '任务日志主键';
comment on column sys_job_log.job_name is '任务名称';
comment on column sys_job_log.job_group is '任务组名';
comment on column sys_job_log.invoke_target is '调用目标字符串';
comment on column sys_job_log.status is '执行状态（0正常 1失败）';
comment on column sys_job_log.msg is '异常消息';
comment on column sys_job_log.create_time is '创建时间';

create index idx_sys_job_log_ct on sys_job_log(create_time);
create index idx_sys_job_log_s on sys_job_log(status);
select setval(pg_get_serial_sequence('sys_job_log', 'job_log_id'), (select max(job_log_id) from sys_job_log));


-- ----------------------------
-- 18、在线用户记录
-- ----------------------------
drop table if exists sys_user_online;
create table sys_user_online (
  session_id        varchar(50)   not null,
  login_name        varchar(50)   default '',
  dept_name         varchar(50)   default '',
  ipaddr            varchar(128)  default '',
  login_location    varchar(255)  default '',
  browser           varchar(50)   default '',
  os                varchar(50)   default '',
  status            varchar(10)   default '',
  start_timestamp   timestamp,
  last_access_time  timestamp,
  expire_time       integer       default 0,
  session_data      bytea         default null,
  primary key (session_id)
);
comment on table sys_user_online is '在线用户记录';
comment on column sys_user_online.session_id is '用户会话id';
comment on column sys_user_online.login_name is '登录账号';
comment on column sys_user_online.dept_name is '部门名称';
comment on column sys_user_online.ipaddr is '登录IP地址';
comment on column sys_user_online.login_location is '登录地点';
comment on column sys_user_online.browser is '浏览器类型';
comment on column sys_user_online.os is '操作系统';
comment on column sys_user_online.status is '在线状态on_line在线off_line离线';
comment on column sys_user_online.start_timestamp is 'session创建时间';
comment on column sys_user_online.last_access_time is 'session最后访问时间';
comment on column sys_user_online.expire_time is '超时时间，单位为分钟';
comment on column sys_user_online.session_data is '序列化的Session数据，用于服务重启后恢复会话';


-- ----------------------------
-- Quartz 定时任务相关表
-- ----------------------------

drop table if exists QRTZ_FIRED_TRIGGERS;
drop table if exists QRTZ_PAUSED_TRIGGER_GRPS;
drop table if exists QRTZ_SCHEDULER_STATE;
drop table if exists QRTZ_LOCKS;
drop table if exists QRTZ_SIMPROP_TRIGGERS;
drop table if exists QRTZ_SIMPLE_TRIGGERS;
drop table if exists QRTZ_CRON_TRIGGERS;
drop table if exists QRTZ_BLOB_TRIGGERS;
drop table if exists QRTZ_TRIGGERS;
drop table if exists QRTZ_JOB_DETAILS;
drop table if exists QRTZ_CALENDARS;

-- ----------------------------
-- 1、存储每一个已配置的 jobDetail 的详细信息
-- ----------------------------
create table QRTZ_JOB_DETAILS (
    sched_name           varchar(120)    not null,
    job_name             varchar(200)    not null,
    job_group            varchar(200)    not null,
    description          varchar(250)    null,
    job_class_name       varchar(250)    not null,
    is_durable           varchar(1)      not null,
    is_nonconcurrent     varchar(1)      not null,
    is_update_data       varchar(1)      not null,
    requests_recovery    varchar(1)      not null,
    job_data             bytea           null,
    primary key (sched_name, job_name, job_group)
);
comment on table QRTZ_JOB_DETAILS is '任务详细信息表';
comment on column QRTZ_JOB_DETAILS.sched_name is '调度名称';
comment on column QRTZ_JOB_DETAILS.job_name is '任务名称';
comment on column QRTZ_JOB_DETAILS.job_group is '任务组名';
comment on column QRTZ_JOB_DETAILS.description is '相关介绍';
comment on column QRTZ_JOB_DETAILS.job_class_name is '执行任务类名称';
comment on column QRTZ_JOB_DETAILS.is_durable is '是否持久化';
comment on column QRTZ_JOB_DETAILS.is_nonconcurrent is '是否并发';
comment on column QRTZ_JOB_DETAILS.is_update_data is '是否更新数据';
comment on column QRTZ_JOB_DETAILS.requests_recovery is '是否接受恢复执行';
comment on column QRTZ_JOB_DETAILS.job_data is '存放持久化job对象';

-- ----------------------------
-- 2、 存储已配置的 Trigger 的信息
-- ----------------------------
create table QRTZ_TRIGGERS (
    sched_name           varchar(120)    not null,
    trigger_name         varchar(200)    not null,
    trigger_group        varchar(200)    not null,
    job_name             varchar(200)    not null,
    job_group            varchar(200)    not null,
    description          varchar(250)    null,
    next_fire_time       bigint          null,
    prev_fire_time       bigint          null,
    priority             integer         null,
    trigger_state        varchar(16)     not null,
    trigger_type         varchar(8)      not null,
    start_time           bigint          not null,
    end_time             bigint          null,
    calendar_name        varchar(200)    null,
    misfire_instr        smallint        null,
    job_data             bytea           null,
    primary key (sched_name, trigger_name, trigger_group)
);
comment on table QRTZ_TRIGGERS is '触发器详细信息表';
comment on column QRTZ_TRIGGERS.sched_name is '调度名称';
comment on column QRTZ_TRIGGERS.trigger_name is '触发器的名字';
comment on column QRTZ_TRIGGERS.trigger_group is '触发器所属组的名字';
comment on column QRTZ_TRIGGERS.job_name is 'qrtz_job_details表job_name的外键';
comment on column QRTZ_TRIGGERS.job_group is 'qrtz_job_details表job_group的外键';
comment on column QRTZ_TRIGGERS.description is '相关介绍';
comment on column QRTZ_TRIGGERS.next_fire_time is '上一次触发时间（毫秒）';
comment on column QRTZ_TRIGGERS.prev_fire_time is '下一次触发时间（默认为-1表示不触发）';
comment on column QRTZ_TRIGGERS.priority is '优先级';
comment on column QRTZ_TRIGGERS.trigger_state is '触发器状态';
comment on column QRTZ_TRIGGERS.trigger_type is '触发器的类型';
comment on column QRTZ_TRIGGERS.start_time is '开始时间';
comment on column QRTZ_TRIGGERS.end_time is '结束时间';
comment on column QRTZ_TRIGGERS.calendar_name is '日程表名称';
comment on column QRTZ_TRIGGERS.misfire_instr is '补偿执行的策略';
comment on column QRTZ_TRIGGERS.job_data is '存放持久化job对象';

-- ----------------------------
-- 3、 存储简单的 Trigger，包括重复次数，间隔，以及已触发的次数
-- ----------------------------
create table QRTZ_SIMPLE_TRIGGERS (
    sched_name           varchar(120)    not null,
    trigger_name         varchar(200)    not null,
    trigger_group        varchar(200)    not null,
    repeat_count         bigint          not null,
    repeat_interval      bigint          not null,
    times_triggered      bigint          not null,
    primary key (sched_name, trigger_name, trigger_group)
);
comment on table QRTZ_SIMPLE_TRIGGERS is '简单触发器的信息表';
comment on column QRTZ_SIMPLE_TRIGGERS.sched_name is '调度名称';
comment on column QRTZ_SIMPLE_TRIGGERS.trigger_name is 'qrtz_triggers表trigger_name的外键';
comment on column QRTZ_SIMPLE_TRIGGERS.trigger_group is 'qrtz_triggers表trigger_group的外键';
comment on column QRTZ_SIMPLE_TRIGGERS.repeat_count is '重复的次数统计';
comment on column QRTZ_SIMPLE_TRIGGERS.repeat_interval is '重复的间隔时间';
comment on column QRTZ_SIMPLE_TRIGGERS.times_triggered is '已经触发的次数';

-- ----------------------------
-- 4、 存储 Cron Trigger，包括 Cron 表达式和时区信息
-- ----------------------------
create table QRTZ_CRON_TRIGGERS (
    sched_name           varchar(120)    not null,
    trigger_name         varchar(200)    not null,
    trigger_group        varchar(200)    not null,
    cron_expression      varchar(200)    not null,
    time_zone_id         varchar(80),
    primary key (sched_name, trigger_name, trigger_group)
);
comment on table QRTZ_CRON_TRIGGERS is 'Cron类型的触发器表';
comment on column QRTZ_CRON_TRIGGERS.sched_name is '调度名称';
comment on column QRTZ_CRON_TRIGGERS.trigger_name is 'qrtz_triggers表trigger_name的外键';
comment on column QRTZ_CRON_TRIGGERS.trigger_group is 'qrtz_triggers表trigger_group的外键';
comment on column QRTZ_CRON_TRIGGERS.cron_expression is 'cron表达式';
comment on column QRTZ_CRON_TRIGGERS.time_zone_id is '时区';

-- ----------------------------
-- 5、 Trigger 作为 Blob 类型存储
-- ----------------------------
create table QRTZ_BLOB_TRIGGERS (
    sched_name           varchar(120)    not null,
    trigger_name         varchar(200)    not null,
    trigger_group        varchar(200)    not null,
    blob_data            bytea           null,
    primary key (sched_name, trigger_name, trigger_group)
);
comment on table QRTZ_BLOB_TRIGGERS is 'Blob类型的触发器表';
comment on column QRTZ_BLOB_TRIGGERS.sched_name is '调度名称';
comment on column QRTZ_BLOB_TRIGGERS.trigger_name is 'qrtz_triggers表trigger_name的外键';
comment on column QRTZ_BLOB_TRIGGERS.trigger_group is 'qrtz_triggers表trigger_group的外键';
comment on column QRTZ_BLOB_TRIGGERS.blob_data is '存放持久化Trigger对象';

-- ----------------------------
-- 6、 以 Blob 类型存储存放日历信息
-- ----------------------------
create table QRTZ_CALENDARS (
    sched_name           varchar(120)    not null,
    calendar_name        varchar(200)    not null,
    calendar             bytea           not null,
    primary key (sched_name, calendar_name)
);
comment on table QRTZ_CALENDARS is '日历信息表';
comment on column QRTZ_CALENDARS.sched_name is '调度名称';
comment on column QRTZ_CALENDARS.calendar_name is '日历名称';
comment on column QRTZ_CALENDARS.calendar is '存放持久化calendar对象';

-- ----------------------------
-- 7、 存储已暂停的 Trigger 组的信息
-- ----------------------------
create table QRTZ_PAUSED_TRIGGER_GRPS (
    sched_name           varchar(120)    not null,
    trigger_group        varchar(200)    not null,
    primary key (sched_name, trigger_group)
);
comment on table QRTZ_PAUSED_TRIGGER_GRPS is '暂停的触发器表';
comment on column QRTZ_PAUSED_TRIGGER_GRPS.sched_name is '调度名称';
comment on column QRTZ_PAUSED_TRIGGER_GRPS.trigger_group is 'qrtz_triggers表trigger_group的外键';

-- ----------------------------
-- 8、 存储与已触发的 Trigger 相关的状态信息
-- ----------------------------
create table QRTZ_FIRED_TRIGGERS (
    sched_name           varchar(120)    not null,
    entry_id             varchar(95)     not null,
    trigger_name         varchar(200)    not null,
    trigger_group        varchar(200)    not null,
    instance_name        varchar(200)    not null,
    fired_time           bigint          not null,
    sched_time           bigint          not null,
    priority             integer         not null,
    state                varchar(16)     not null,
    job_name             varchar(200)    null,
    job_group            varchar(200)    null,
    is_nonconcurrent     varchar(1)      null,
    requests_recovery    varchar(1)      null,
    primary key (sched_name, entry_id)
);
comment on table QRTZ_FIRED_TRIGGERS is '已触发的触发器表';
comment on column QRTZ_FIRED_TRIGGERS.sched_name is '调度名称';
comment on column QRTZ_FIRED_TRIGGERS.entry_id is '调度器实例id';
comment on column QRTZ_FIRED_TRIGGERS.trigger_name is 'qrtz_triggers表trigger_name的外键';
comment on column QRTZ_FIRED_TRIGGERS.trigger_group is 'qrtz_triggers表trigger_group的外键';
comment on column QRTZ_FIRED_TRIGGERS.instance_name is '调度器实例名';
comment on column QRTZ_FIRED_TRIGGERS.fired_time is '触发的时间';
comment on column QRTZ_FIRED_TRIGGERS.sched_time is '定时器制定的时间';
comment on column QRTZ_FIRED_TRIGGERS.priority is '优先级';
comment on column QRTZ_FIRED_TRIGGERS.state is '状态';
comment on column QRTZ_FIRED_TRIGGERS.job_name is '任务名称';
comment on column QRTZ_FIRED_TRIGGERS.job_group is '任务组名';
comment on column QRTZ_FIRED_TRIGGERS.is_nonconcurrent is '是否并发';
comment on column QRTZ_FIRED_TRIGGERS.requests_recovery is '是否接受恢复执行';

-- ----------------------------
-- 9、 存储少量的有关 Scheduler 的状态信息
-- ----------------------------
create table QRTZ_SCHEDULER_STATE (
    sched_name           varchar(120)    not null,
    instance_name        varchar(200)    not null,
    last_checkin_time    bigint          not null,
    checkin_interval     bigint          not null,
    primary key (sched_name, instance_name)
);
comment on table QRTZ_SCHEDULER_STATE is '调度器状态表';
comment on column QRTZ_SCHEDULER_STATE.sched_name is '调度名称';
comment on column QRTZ_SCHEDULER_STATE.instance_name is '实例名称';
comment on column QRTZ_SCHEDULER_STATE.last_checkin_time is '上次检查时间';
comment on column QRTZ_SCHEDULER_STATE.checkin_interval is '检查间隔时间';

-- ----------------------------
-- 10、 存储程序的悲观锁的信息
-- ----------------------------
create table QRTZ_LOCKS (
    sched_name           varchar(120)    not null,
    lock_name            varchar(40)     not null,
    primary key (sched_name, lock_name)
);
comment on table QRTZ_LOCKS is '存储的悲观锁信息表';
comment on column QRTZ_LOCKS.sched_name is '调度名称';
comment on column QRTZ_LOCKS.lock_name is '悲观锁名称';

-- ----------------------------
-- 11、 Quartz集群实现同步机制的行锁表
-- ----------------------------
create table QRTZ_SIMPROP_TRIGGERS (
    sched_name           varchar(120)    not null,
    trigger_name         varchar(200)    not null,
    trigger_group        varchar(200)    not null,
    str_prop_1           varchar(512)    null,
    str_prop_2           varchar(512)    null,
    str_prop_3           varchar(512)    null,
    int_prop_1           integer         null,
    int_prop_2           integer         null,
    long_prop_1          bigint          null,
    long_prop_2          bigint          null,
    dec_prop_1           numeric(13,4)   null,
    dec_prop_2           numeric(13,4)   null,
    bool_prop_1          varchar(1)      null,
    bool_prop_2          varchar(1)      null,
    primary key (sched_name, trigger_name, trigger_group)
);
comment on table QRTZ_SIMPROP_TRIGGERS is '同步机制的行锁表';
comment on column QRTZ_SIMPROP_TRIGGERS.sched_name is '调度名称';
comment on column QRTZ_SIMPROP_TRIGGERS.trigger_name is 'qrtz_triggers表trigger_name的外键';
comment on column QRTZ_SIMPROP_TRIGGERS.trigger_group is 'qrtz_triggers表trigger_group的外键';
comment on column QRTZ_SIMPROP_TRIGGERS.str_prop_1 is 'String类型的trigger的第一个参数';
comment on column QRTZ_SIMPROP_TRIGGERS.str_prop_2 is 'String类型的trigger的第二个参数';
comment on column QRTZ_SIMPROP_TRIGGERS.str_prop_3 is 'String类型的trigger的第三个参数';
comment on column QRTZ_SIMPROP_TRIGGERS.int_prop_1 is 'int类型的trigger的第一个参数';
comment on column QRTZ_SIMPROP_TRIGGERS.int_prop_2 is 'int类型的trigger的第二个参数';
comment on column QRTZ_SIMPROP_TRIGGERS.long_prop_1 is 'long类型的trigger的第一个参数';
comment on column QRTZ_SIMPROP_TRIGGERS.long_prop_2 is 'long类型的trigger的第二个参数';
comment on column QRTZ_SIMPROP_TRIGGERS.dec_prop_1 is 'decimal类型的trigger的第一个参数';
comment on column QRTZ_SIMPROP_TRIGGERS.dec_prop_2 is 'decimal类型的trigger的第二个参数';
comment on column QRTZ_SIMPROP_TRIGGERS.bool_prop_1 is 'Boolean类型的trigger的第一个参数';
comment on column QRTZ_SIMPROP_TRIGGERS.bool_prop_2 is 'Boolean类型的trigger的第二个参数';